#https://hub.docker.com/_/tomcat/
FROM tomcat:7
ADD ./lib/postgresql-9.2.jdbc4-20130510.104442-6.jar /usr/local/tomcat/lib/postgresql-9.2.jdbc4-20130510.104442-6.jar
ADD ./context.xml /usr/local/tomcat/conf/context.xml